### ISSUE TITLE
multiple q-points report errors

### ISSUE THREAD

**Issue by Liangzhang545** [mir-group/phoebe#187]
Dear Sir
I met  multiple q-points report errors when calculating thermal conductivity. It is OK when q point is 1*1*1 (mpirun thermal_conductivity -qg 1 1 1 --temperature 300). It return error (Error mapping operations backwards) when q point is 2*2*1 or even densier q point mesh (mpirun thermal_conductivity -qg 2 2 1 --temperature 300). The attach files are input files
![a](https://github.com/mir-group/phoebe/assets/99186979/d0fd93af-cb9e-4bc8-bf46-16538c5a3bee)
![b](https://github.com/mir-group/phoebe/assets/99186979/b6acc3d6-6e78-438e-a2c3-e62ec0eafc1e)
[infile.zip](https://github.com/mir-group/phoebe/files/11644802/infile.zip)

**Comment by jcoulter12** [comment]
Hi @Liangzhang545 -- 

This isn't a screenshot of a Phoebe calculation, so I think you've posted it on the wrong code package's github repository. 
If this is a ShengBTE calculation or otherwise, you should post the issue on the relevant code package's github repository. 

Not only that, but to calculate the thermal conductivity with so few points doesn't make sense, regardless of what code you use.

If you want to calculate the thermal conductivity using Phoebe, you can do that with force constants from ShengBTE... but that's something entirely different than whatever this is. 

Because this issue isn't about Phoebe, I'm going to close the issue. Please let us know if you have an issue related to using the Phoebe code. 
Jenny
