### ISSUE TITLE
Improve copying in ParallelMatrix::diagonalize for call to pdsyev

### ISSUE THREAD

**Issue by jcoulter12** [mir-group/phoebe#65]
Currently, in ParallelMatrix::diagonalize, a copy of the current PMatrix object is made (called eigenvectors) to be used as an output to a pdsyev call. This is done because both the input and output PMatrices used by pdsyev must have the same blacs context object. However, this copy creation for the output matrix is not as efficient as it should be, because we only want to copy the properties (not the data) of the matrix being diagonalized.  

This is not a high priority, but it should likely be improved at some point.

**Comment by cepellotti** [comment]
Please note that there currently is an unwanted effect. On exit, Pdsyev changes the values of the matrix that has been diagonalized. It's probably more honest to copy "this.mat" to a temporary matrix, so that "this.mat" is left unchanged. 
For the eigenvectors object, we could use the default initializer and then simply manually set the value of blacsContext (we can do that within the class implementation).

**Comment by jcoulter12** [comment]
Thanks for noticing this issue, that's definitely a big mistake -- do you have these changes made on your current branch, or shall I make them in my next pull request?

**Comment by cepellotti** [comment]
No, I didn't change them anywhere. Please go ahead and correct them in your next pull request.
